security:
    # Password hashers configuration
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        App\Entity\User:
            algorithm: auto

    # User providers configuration
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    # Firewalls configuration
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # Main firewall for authenticated areas
        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\LoginFormAuthenticator
            logout:
                path: app_logout
                target: app_login

        # Firewall for public access to the URL creation route
        create_url:
            pattern: ^/create
            security: false

    # Role hierarchy definition
    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER]

    # Access control rules
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/tag, roles: ROLE_ADMIN }
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/create, roles: PUBLIC_ACCESS }
        - { path: ^/url/create, roles: PUBLIC_ACCESS }
        - { path: ^/[a-zA-Z0-9]+, roles: PUBLIC_ACCESS }
        - { path: ^/, roles: PUBLIC_ACCESS }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
